### ISSUE TITLE
Add template for Ruby linter config (RuboCop?)

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#144]
For many consumers of Hatchet, I would imagine that Ruby isn't their primary language. As such, I think it's worth encouraging use of a linter to help guide them towards best practices and potentially catch hard to debug bugs from misunderstanding Ruby idioms.

One way to do this (and reduce the effort of setting a linter up), would be for Hatchet init to include a RoboCop template. There may also be additional plugins that would be useful (eg rubocop-rspec).

@schneems Thoughts? :-)

**Comment by schneems** [comment]
For adding rubocop to this library directly: Rubocop currently only supports Ruby 2.4+ and we need to support back to Heroku-16 which has Ruby 2.2 (see https://github.com/heroku/platform-api/pull/110)

For adding it to `hatchet init` i'm for it, but i'm not srue about that incompatibility between newer and older rubies. My personal experience with rubocop is it works best for formatting and styling things when you have multiple contributors and don't want to argue about style in PRs. It does have some logic rules such as catching single equal instead of double equal in `if` statements, but my perception is that just because the linter says things are okay...since there aren't types (yet) it's a very weak guarantee. 

I'm not totally sure how to square all of that.

**Comment by edmorley** [comment]
Yeah I was meaning just for `hatchet init`, not for this repo, and not worrying about support for older Rubies, since I would presume that `hatchet init` is primarily being used by newer projects that are not on old Ruby.

> It does have some logic rules such as catching single equal instead of double equal in if statements

Yeah I was thinking of these kind of footguns. However if there aren't many of these types of checks, then perhaps it's not as worth it as for some other language's linters.

**Comment by edmorley** [comment]
I enabled rubocop linting for Python in:
heroku/heroku-buildpack-python/pull/1141
