### ISSUE TITLE
Support configuring the default stack

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#163]
A common pattern for buildpacks is to run their Hatchet tests on CI against all stacks, with each stack in a separate job. And then when run locally the Hatchet tests are run against a single default stack.

At the moment Hatchet only allows configuring the stack during the instantiation of each test (in the `Hatchet::Runner.new()` call).

This means that every test has to pass in the stack explicitly, or else use a helper method to create the app. eg:

```ruby
DEFAULT_STACK = ENV['STACK'] || 'heroku-18'

def new_app(*args, **kwargs)
  kwargs[:stack] ||= DEFAULT_STACK
  Hatchet::Runner.new(*args, **kwargs)
end
```

It would be great if there was a way to configure the default Hatchet stack via an env var (that would still allow overriding when calling `Hatchet::Runner.new()` if desired).

**Comment by schneems** [comment]
The Ruby buildpack doesn't use this pattern because we have separate tests for binaries on individual stacks. We do sometimes special case for an individual stack test, but by and large all behavior that we test is not stack specific.

That being said I see the desire to do this. I think a global env var would be useful.:

```ruby
ENV["HATCHET_DEFAULT_STACK"]
```

My only concerns/thoughts would be if someone is accidentally setting this, and thinking their buildpack works against the latest stack, only to find out that it doesn't (because it's not running on the latest heroku default stack). 

We probably want a way to trigger an escape valve. Maybe passing in `stack: :current` or `stack: :latest` to `Hatchet::Runner.new` could revert the use of a global env var.
